package com.madera.sys_madera.integration;

import com.madera.sys_madera.model.Client;
import com.madera.sys_madera.model.ERole;
import com.madera.sys_madera.model.Furniture;
import com.madera.sys_madera.model.Invoice;
import com.madera.sys_madera.model.Order;
import com.madera.sys_madera.model.OrderDetail;
import com.madera.sys_madera.model.Role;
import com.madera.sys_madera.model.User;
import com.madera.sys_madera.model.WoodInventory;
import com.madera.sys_madera.model.WoodSurplus;
import com.madera.sys_madera.repository.ClientRepository;
import com.madera.sys_madera.repository.FurnitureRepository;
import com.madera.sys_madera.repository.InvoiceRepository;
import com.madera.sys_madera.repository.OrderRepository;
import com.madera.sys_madera.repository.RoleRepository;
import com.madera.sys_madera.repository.UserRepository;
import com.madera.sys_madera.repository.WoodInventoryRepository;
import com.madera.sys_madera.repository.WoodSurplusRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
@DisplayName("Audit fields (createdAt / updatedAt)")
class AuditIntegrationTest {

    @Autowired
    private FurnitureRepository furnitureRepository;

    @Autowired
    private ClientRepository clientRepository;

    @Autowired
    private WoodInventoryRepository woodInventoryRepository;

    @Autowired
    private WoodSurplusRepository woodSurplusRepository;

    @Autowired
    private InvoiceRepository invoiceRepository;

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private RoleRepository roleRepository;

    @PersistenceContext
    private EntityManager entityManager;

    @BeforeEach
    void cleanUp() {
        invoiceRepository.deleteAll();
        orderRepository.deleteAll();
        woodSurplusRepository.deleteAll();
        userRepository.findAll().forEach(u -> {
            u.getRoles().clear();
            userRepository.save(u);
        });
        userRepository.deleteAll();
        clientRepository.deleteAll();
        furnitureRepository.deleteAll();
        woodInventoryRepository.deleteAll();
        roleRepository.deleteAll();
    }

    @Nested
    @DisplayName("Furniture")
    class FurnitureAudit {

        @Test
        @DisplayName("createdAt should be auto-generated on persist")
        void createdAt_shouldBeAutoGenerated() {
            var entity = Furniture.builder()
                    .name("Mesa Roble").price(new BigDecimal("350.00")).stockQuantity(10)
                    .build();

            var saved = furnitureRepository.saveAndFlush(entity);

            assertThat(saved.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("updatedAt should be set on initial persist")
        void updatedAt_shouldBeSet_onCreate() {
            var entity = Furniture.builder()
                    .name("Silla Pino").price(new BigDecimal("85.00")).stockQuantity(25)
                    .build();

            var saved = furnitureRepository.saveAndFlush(entity);

            assertThat(saved.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("createdAt should remain unchanged after update")
        void createdAt_shouldRemainUnchanged_afterUpdate() throws Exception {
            var saved = furnitureRepository.saveAndFlush(Furniture.builder()
                    .name("Estante").price(new BigDecimal("200.00")).stockQuantity(5)
                    .build());
            entityManager.clear();
            var originalCreatedAt = furnitureRepository.findById(saved.getId()).orElseThrow().getCreatedAt();

            Thread.sleep(10);
            var toUpdate = furnitureRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setName("Estante Premium");
            furnitureRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = furnitureRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getCreatedAt()).isEqualTo(originalCreatedAt);
        }

        @Test
        @DisplayName("updatedAt should change after update")
        void updatedAt_shouldChange_afterUpdate() throws Exception {
            var saved = furnitureRepository.saveAndFlush(Furniture.builder()
                    .name("Cómoda").price(new BigDecimal("800.00")).stockQuantity(3)
                    .build());
            entityManager.clear();
            var originalUpdatedAt = furnitureRepository.findById(saved.getId()).orElseThrow().getUpdatedAt();

            Thread.sleep(10);
            var toUpdate = furnitureRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setPrice(new BigDecimal("900.00"));
            furnitureRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = furnitureRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getUpdatedAt()).isAfter(originalUpdatedAt);
        }
    }

    @Nested
    @DisplayName("Client")
    class ClientAudit {

        @Test
        @DisplayName("createdAt should be auto-generated on persist")
        void createdAt_shouldBeAutoGenerated() {
            var entity = Client.builder()
                    .name("Juan Pérez").email("juan@example.com")
                    .build();

            var saved = clientRepository.saveAndFlush(entity);

            assertThat(saved.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("updatedAt should be set on initial persist")
        void updatedAt_shouldBeSet_onCreate() {
            var entity = Client.builder()
                    .name("María García").email("maria@example.com")
                    .build();

            var saved = clientRepository.saveAndFlush(entity);

            assertThat(saved.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("createdAt should remain unchanged after update")
        void createdAt_shouldRemainUnchanged_afterUpdate() throws Exception {
            var saved = clientRepository.saveAndFlush(Client.builder()
                    .name("Carlos López").email("carlos@example.com")
                    .build());
            entityManager.clear();
            var originalCreatedAt = clientRepository.findById(saved.getId()).orElseThrow().getCreatedAt();

            Thread.sleep(10);
            var toUpdate = clientRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setName("Carlos López Actualizado");
            clientRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = clientRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getCreatedAt()).isEqualTo(originalCreatedAt);
        }

        @Test
        @DisplayName("updatedAt should change after update")
        void updatedAt_shouldChange_afterUpdate() throws Exception {
            var saved = clientRepository.saveAndFlush(Client.builder()
                    .name("Ana Martínez").email("ana@example.com")
                    .build());
            entityManager.clear();
            var originalUpdatedAt = clientRepository.findById(saved.getId()).orElseThrow().getUpdatedAt();

            Thread.sleep(10);
            var toUpdate = clientRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setAddress("Calle Nueva 456");
            clientRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = clientRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getUpdatedAt()).isAfter(originalUpdatedAt);
        }
    }

    @Nested
    @DisplayName("WoodInventory")
    class WoodInventoryAudit {

        @Test
        @DisplayName("createdAt should be auto-generated on persist")
        void createdAt_shouldBeAutoGenerated() {
            var entity = WoodInventory.builder()
                    .woodType("Roble").quantity(new BigDecimal("50.00"))
                    .unit("m3").unitPrice(new BigDecimal("1200.00"))
                    .build();

            var saved = woodInventoryRepository.saveAndFlush(entity);

            assertThat(saved.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("updatedAt should be set on initial persist")
        void updatedAt_shouldBeSet_onCreate() {
            var entity = WoodInventory.builder()
                    .woodType("Pino").quantity(new BigDecimal("100.00"))
                    .unit("m3").unitPrice(new BigDecimal("800.00"))
                    .build();

            var saved = woodInventoryRepository.saveAndFlush(entity);

            assertThat(saved.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("createdAt should remain unchanged after update")
        void createdAt_shouldRemainUnchanged_afterUpdate() throws Exception {
            var saved = woodInventoryRepository.saveAndFlush(WoodInventory.builder()
                    .woodType("Caoba").quantity(new BigDecimal("20.00"))
                    .unit("m3").unitPrice(new BigDecimal("2500.00"))
                    .build());
            entityManager.clear();
            var originalCreatedAt = woodInventoryRepository.findById(saved.getId()).orElseThrow().getCreatedAt();

            Thread.sleep(10);
            var toUpdate = woodInventoryRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setQuantity(new BigDecimal("25.00"));
            woodInventoryRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = woodInventoryRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getCreatedAt()).isEqualTo(originalCreatedAt);
        }

        @Test
        @DisplayName("updatedAt should change after update")
        void updatedAt_shouldChange_afterUpdate() throws Exception {
            var saved = woodInventoryRepository.saveAndFlush(WoodInventory.builder()
                    .woodType("Cedro").quantity(new BigDecimal("30.00"))
                    .unit("m3").unitPrice(new BigDecimal("1800.00"))
                    .build());
            entityManager.clear();
            var originalUpdatedAt = woodInventoryRepository.findById(saved.getId()).orElseThrow().getUpdatedAt();

            Thread.sleep(10);
            var toUpdate = woodInventoryRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setUnitPrice(new BigDecimal("1900.00"));
            woodInventoryRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = woodInventoryRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getUpdatedAt()).isAfter(originalUpdatedAt);
        }
    }

    @Nested
    @DisplayName("WoodSurplus")
    class WoodSurplusAudit {

        @Test
        @DisplayName("createdAt should be auto-generated on persist")
        void createdAt_shouldBeAutoGenerated() {
            var entity = WoodSurplus.builder()
                    .woodType("Roble").quantity(new BigDecimal("5.50"))
                    .unit("m2").description("Sobrante de mesa")
                    .build();

            var saved = woodSurplusRepository.saveAndFlush(entity);

            assertThat(saved.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("updatedAt should be set on initial persist")
        void updatedAt_shouldBeSet_onCreate() {
            var entity = WoodSurplus.builder()
                    .woodType("Pino").quantity(new BigDecimal("3.00"))
                    .unit("m2")
                    .build();

            var saved = woodSurplusRepository.saveAndFlush(entity);

            assertThat(saved.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("createdAt should remain unchanged after update")
        void createdAt_shouldRemainUnchanged_afterUpdate() throws Exception {
            var saved = woodSurplusRepository.saveAndFlush(WoodSurplus.builder()
                    .woodType("Caoba").quantity(new BigDecimal("2.00"))
                    .unit("m2")
                    .build());
            entityManager.clear();
            var originalCreatedAt = woodSurplusRepository.findById(saved.getId()).orElseThrow().getCreatedAt();

            Thread.sleep(10);
            var toUpdate = woodSurplusRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setQuantity(new BigDecimal("2.50"));
            woodSurplusRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = woodSurplusRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getCreatedAt()).isEqualTo(originalCreatedAt);
        }

        @Test
        @DisplayName("updatedAt should change after update")
        void updatedAt_shouldChange_afterUpdate() throws Exception {
            var saved = woodSurplusRepository.saveAndFlush(WoodSurplus.builder()
                    .woodType("Cedro").quantity(new BigDecimal("1.50"))
                    .unit("m2")
                    .build());
            entityManager.clear();
            var originalUpdatedAt = woodSurplusRepository.findById(saved.getId()).orElseThrow().getUpdatedAt();

            Thread.sleep(10);
            var toUpdate = woodSurplusRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setDescription("Sobrante actualizado");
            woodSurplusRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = woodSurplusRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getUpdatedAt()).isAfter(originalUpdatedAt);
        }
    }

    @Nested
    @DisplayName("User")
    class UserAudit {

        private Role role;

        @BeforeEach
        void setUp() {
            role = roleRepository.saveAndFlush(Role.builder().name(ERole.ROLE_ADMIN).build());
        }

        @Test
        @DisplayName("createdAt should be auto-generated on persist")
        void createdAt_shouldBeAutoGenerated() {
            var entity = User.builder()
                    .username("testuser").email("test@example.com")
                    .password("encoded123").firstName("Test").lastName("User")
                    .roles(Set.of(role))
                    .build();

            var saved = userRepository.saveAndFlush(entity);

            assertThat(saved.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("updatedAt should be set on initial persist")
        void updatedAt_shouldBeSet_onCreate() {
            var entity = User.builder()
                    .username("testuser2").email("test2@example.com")
                    .password("encoded456").firstName("Test2").lastName("User2")
                    .roles(Set.of(role))
                    .build();

            var saved = userRepository.saveAndFlush(entity);

            assertThat(saved.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("createdAt should remain unchanged after update")
        void createdAt_shouldRemainUnchanged_afterUpdate() throws Exception {
            var saved = userRepository.saveAndFlush(User.builder()
                    .username("user3").email("user3@example.com")
                    .password("pass").firstName("Name3").lastName("Last3")
                    .roles(Set.of(role))
                    .build());
            entityManager.clear();
            var originalCreatedAt = userRepository.findById(saved.getId()).orElseThrow().getCreatedAt();

            Thread.sleep(10);
            var toUpdate = userRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setFirstName("Name3 Updated");
            userRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = userRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getCreatedAt()).isEqualTo(originalCreatedAt);
        }

        @Test
        @DisplayName("updatedAt should change after update")
        void updatedAt_shouldChange_afterUpdate() throws Exception {
            var saved = userRepository.saveAndFlush(User.builder()
                    .username("user4").email("user4@example.com")
                    .password("pass").firstName("Name4").lastName("Last4")
                    .roles(Set.of(role))
                    .build());
            entityManager.clear();
            var originalUpdatedAt = userRepository.findById(saved.getId()).orElseThrow().getUpdatedAt();

            Thread.sleep(10);
            var toUpdate = userRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setLastName("Last4 Updated");
            userRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = userRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getUpdatedAt()).isAfter(originalUpdatedAt);
        }
    }

    private OrderDetail buildDetail(Furniture furniture, int quantity, BigDecimal unitPrice, Order order) {
        var d = OrderDetail.builder()
                .quantity(quantity).unitPrice(unitPrice)
                .subtotal(unitPrice.multiply(BigDecimal.valueOf(quantity)))
                .furniture(furniture)
                .build();
        d.setOrder(order);
        return d;
    }

    @Nested
    @DisplayName("Order")
    class OrderAudit {

        private Client client;
        private Furniture furniture;

        @BeforeEach
        void setUp() {
            client = clientRepository.saveAndFlush(Client.builder()
                    .name("Cliente Orden").email("orden@example.com").build());
            furniture = furnitureRepository.saveAndFlush(Furniture.builder()
                    .name("Mueble Orden").price(new BigDecimal("500.00")).stockQuantity(10).build());
        }

        @Test
        @DisplayName("createdAt should be auto-generated on persist")
        void createdAt_shouldBeAutoGenerated() {
            var order = new Order();
            order.setOrderNumber("ORD-001");
            order.setTotalAmount(new BigDecimal("500.00"));
            order.setClient(client);
            var detail = buildDetail(furniture, 1, new BigDecimal("500.00"), order);
            order.setOrderDetails(List.of(detail));

            var saved = orderRepository.saveAndFlush(order);

            assertThat(saved.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("updatedAt should be set on initial persist")
        void updatedAt_shouldBeSet_onCreate() {
            var order = new Order();
            order.setOrderNumber("ORD-002");
            order.setTotalAmount(new BigDecimal("1000.00"));
            order.setClient(client);
            var detail = buildDetail(furniture, 2, new BigDecimal("500.00"), order);
            order.setOrderDetails(List.of(detail));

            var saved = orderRepository.saveAndFlush(order);

            assertThat(saved.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("createdAt should remain unchanged after update")
        void createdAt_shouldRemainUnchanged_afterUpdate() throws Exception {
            var order = new Order();
            order.setOrderNumber("ORD-003");
            order.setTotalAmount(new BigDecimal("500.00"));
            order.setClient(client);
            var detail = buildDetail(furniture, 1, new BigDecimal("500.00"), order);
            order.setOrderDetails(List.of(detail));
            var saved = orderRepository.saveAndFlush(order);
            entityManager.clear();
            var originalCreatedAt = orderRepository.findById(saved.getId()).orElseThrow().getCreatedAt();

            Thread.sleep(10);
            var toUpdate = orderRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setNotes("Nota actualizada");
            orderRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = orderRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getCreatedAt()).isEqualTo(originalCreatedAt);
        }

        @Test
        @DisplayName("updatedAt should change after update")
        void updatedAt_shouldChange_afterUpdate() throws Exception {
            var order = new Order();
            order.setOrderNumber("ORD-004");
            order.setTotalAmount(new BigDecimal("750.00"));
            order.setClient(client);
            var detail = buildDetail(furniture, 1, new BigDecimal("750.00"), order);
            order.setOrderDetails(List.of(detail));
            var saved = orderRepository.saveAndFlush(order);
            entityManager.clear();
            var originalUpdatedAt = orderRepository.findById(saved.getId()).orElseThrow().getUpdatedAt();

            Thread.sleep(10);
            var toUpdate = orderRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setNotes("Nota modificada");
            orderRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = orderRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getUpdatedAt()).isAfter(originalUpdatedAt);
        }
    }

    @Nested
    @DisplayName("Invoice")
    class InvoiceAudit {

        private Client client;
        private Furniture furniture;

        @BeforeEach
        void setUp() {
            client = clientRepository.saveAndFlush(Client.builder()
                    .name("Cliente Factura").email("factura@example.com").build());
            furniture = furnitureRepository.saveAndFlush(Furniture.builder()
                    .name("Mueble Factura").price(new BigDecimal("300.00")).stockQuantity(10).build());
        }

        private Order createOrder(String orderNumber, BigDecimal amount) {
            var order = new Order();
            order.setOrderNumber(orderNumber);
            order.setTotalAmount(amount);
            order.setClient(client);
            var detail = buildDetail(furniture, 1, amount, order);
            order.setOrderDetails(List.of(detail));
            return orderRepository.saveAndFlush(order);
        }

        @Test
        @DisplayName("createdAt should be auto-generated on persist")
        void createdAt_shouldBeAutoGenerated() {
            var order = createOrder("ORD-INV-001", new BigDecimal("300.00"));
            var entity = Invoice.builder()
                    .invoiceNumber("INV-001")
                    .issueDate(LocalDate.now())
                    .dueDate(LocalDate.now().plusDays(30))
                    .totalAmount(new BigDecimal("300.00"))
                    .paidAmount(new BigDecimal("300.00"))
                    .order(order)
                    .build();

            var saved = invoiceRepository.saveAndFlush(entity);

            assertThat(saved.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("updatedAt should be set on initial persist")
        void updatedAt_shouldBeSet_onCreate() {
            var order = createOrder("ORD-INV-002", new BigDecimal("500.00"));
            var entity = Invoice.builder()
                    .invoiceNumber("INV-002")
                    .issueDate(LocalDate.now())
                    .dueDate(LocalDate.now().plusDays(30))
                    .totalAmount(new BigDecimal("500.00"))
                    .paidAmount(new BigDecimal("200.00"))
                    .order(order)
                    .build();

            var saved = invoiceRepository.saveAndFlush(entity);

            assertThat(saved.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("createdAt should remain unchanged after update")
        void createdAt_shouldRemainUnchanged_afterUpdate() throws Exception {
            var order = createOrder("ORD-INV-003", new BigDecimal("400.00"));
            var entity = Invoice.builder()
                    .invoiceNumber("INV-003")
                    .issueDate(LocalDate.now())
                    .dueDate(LocalDate.now().plusDays(30))
                    .totalAmount(new BigDecimal("400.00"))
                    .paidAmount(new BigDecimal("100.00"))
                    .order(order)
                    .build();
            var saved = invoiceRepository.saveAndFlush(entity);
            entityManager.clear();
            var originalCreatedAt = invoiceRepository.findById(saved.getId()).orElseThrow().getCreatedAt();

            Thread.sleep(10);
            var toUpdate = invoiceRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setNotes("Nota de factura actualizada");
            invoiceRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = invoiceRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getCreatedAt()).isEqualTo(originalCreatedAt);
        }

        @Test
        @DisplayName("updatedAt should change after update")
        void updatedAt_shouldChange_afterUpdate() throws Exception {
            var order = createOrder("ORD-INV-004", new BigDecimal("600.00"));
            var entity = Invoice.builder()
                    .invoiceNumber("INV-004")
                    .issueDate(LocalDate.now())
                    .dueDate(LocalDate.now().plusDays(30))
                    .totalAmount(new BigDecimal("600.00"))
                    .paidAmount(new BigDecimal("300.00"))
                    .order(order)
                    .build();
            var saved = invoiceRepository.saveAndFlush(entity);
            entityManager.clear();
            var originalUpdatedAt = invoiceRepository.findById(saved.getId()).orElseThrow().getUpdatedAt();

            Thread.sleep(10);
            var toUpdate = invoiceRepository.findById(saved.getId()).orElseThrow();
            toUpdate.setPaidAmount(new BigDecimal("600.00"));
            invoiceRepository.saveAndFlush(toUpdate);
            entityManager.clear();

            var reloaded = invoiceRepository.findById(saved.getId()).orElseThrow();
            assertThat(reloaded.getUpdatedAt()).isAfter(originalUpdatedAt);
        }
    }
}
